name: moblie
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  http: ^1.2.0
  just_audio: ^0.9.38
  rxdart: ^0.27.7
  audio_video_progress_bar: ^2.0.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_fonts: ^6.2.0
  html: ^0.15.4
  cloud_firestore: ^4.15.8
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  firebase_app_check: ^0.2.1+17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/itunes.png"


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/songs.json
    - assets/itunes.jpg
    - assets/background.png
    - assets/itunes.png